### ISSUE TITLE
umbraco 9 support

### ISSUE THREAD

**Issue by qamarkhan84** [sotirisf/Umbraco-VirtualNodes#15]
Hi there ,

is there any plan to support this package to umbraco 9 .

thanks

**Comment by ZioTino** [comment]
Hi @qamarkhan84 
You might want to check out this one: https://github.com/ZioTino/Our.Umbraco.Skipper

**Comment by sotirisf** [comment]
I haven't used Skipper yet but if it does the same job I'll be happy to suggest it as well!
If there's something already developed as a port for v9, no reason to update mine.

**Comment by qamarkhan84** [comment]
> Hi @qamarkhan84 You might want to check out this one: https://github.com/ZioTino/Our.Umbraco.Skipper

Thanks for sharing this
