### ISSUE TITLE
NuGet package built in debug mode?

### ISSUE THREAD

**Issue by gunnim** [sotirisf/Umbraco-VirtualNodes#4]
Is there a reason for this?
Seems like it would be better to distribute the package in release mode.

(I checked with a directory scanning fork of https://assemblyinformation.codeplex.com/)

**Comment by sotirisf** [comment]
Er, you might be correct (and sorry for the huge delay in answering). 
Next version will definitely be in Release mode. Haven't checked yet, but probably forgot to switch to Release.

**Comment by sotirisf** [comment]
New version 1.0.4 is released and nuget package is now in release mode.  Thanks for noticing!
